import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container mx-auto mt-4">
      <Head>
        <title>Course Micro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-blue-500">Saya halaman utama</main>
    </div>
  );
}
